name: CustomAdvancements
version: ${project.version}
main: me.tippie.customadvancements.CustomAdvancements
website: https://tippie.me
author: Tippie
api-version: 1.13
softdepend: [ Essentials, PlaceholderAPI ]
commands:
  customadvancements:
    aliases: [ ca , advancements]
    description: CustomAdvancements base command
permissions:
  customadvancements.command.help:
    default: true
  customadvancements.command.activate:
    default: true
  customadvancements.command.reload:
    default: op
  customadvancements.command.checkprogress:
    default: true
  customadvancements.command.checkprogress.others:
    default: op
  customadvancements.gui:
    default: true
  customadvancements.command.set:
    default: op